os: linux
dist: xenial
sudo: required
language:
    - go
go:
    - 1.10.8

script:
    - go build ./cmd/gptn
    - make gptn
    #- $GOPATH/bin/goveralls -service=travis-ci
    - cp gptn bdd/node
    - cd bdd/node
    - chmod +x gptn
    - python init.py
    - nohup ./gptn &
    - sleep 15
    - netstat -ap | grep gptn
    - cd ../dct
#    - ls /home/travis/gopath/src/github.com/palletone/go-palletone/bdd/logs/
    - ls /home/travis/gopath/src/github.com/palletone/go-palletone/bdd/node/log
    - mkdir ../logs
#    - ./deposit_test.sh 4 > ../logs/deposit_test.log
#    - python -m robot.run -d ../logs -l createTrans.log.html ../testcase/createTrans
#    - python -m robot.run -d ../logs -l ccinvoke.log.html ../testcase/ccinvoke
#    - python -m robot.run -d ../logs -l DigitalIdentityCert.log.html ../DigitalIdentityCert
env:
    global:
        - 'SFTP_KEY=[base64-encoded-rsa-key]'
after_success:
    - killall gptn
    - cd ../uploadLogs
#    - python ftpUpload.py
    - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
    - curl --ftp-create-dirs
        -T /home/travis/gopath/src/github.com/palletone/go-palletone/bdd/node/log/all.log
        --key /tmp/sftp_rsa
        --ftp-port -
        ftp://${YANGYU}:${PASSWORD}@39.105.191.26/pub/all.log

after_failure:
    - killall gptn
    - cd ../uploadLogs
#    - python ftpUpload.py
    - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
    - curl --ftp-create-dirs
        -T /home/travis/gopath/src/github.com/palletone/go-palletone/bdd/node/log/all.log
        --key /tmp/sftp_rsa
        ftp://${YANGYU}:${PASSWORD}@98.142.130.141/yy/all.log

before_install:
    - go get github.com/mattn/goveralls
    - go get -u github.com/palletone/adaptor
    - go get -u github.com/palletone/btc-adaptor
    - go get -u github.com/palletone/eth-adaptor
    - go get -u github.com/palletone/digital-identity/...
    - source ./gomockgen.sh

install:
    - python -V
    - whereis python
    - which python
    - sudo -H pip install --upgrade pip
    - sudo -H pip install robotframework==2.8.5
    - sudo -H pip install requests
    - sudo -H pip install robotframework-requests
    - sudo -H pip install demjson
    - sudo -H pip install pexpect
    - sudo -H apt-get install expect
    #- sudo -H apt-get install jq tcl tk

addons:
    apt:
        update: true

deploy:
    skip_cleanup: true
#    on:
#        branch: certbdd

notifications:
    email: elva1087penny@163.com
    email:
        recipients:
            - elva1087penny@163.com
        on_success: always # default: change
        on_failure: always

