[Ptn]
NetworkId = 1
SyncMode = "fast"
NoPruning = false
LightPeers = 100
DatabaseCache = 768
TrieCache = 256
TrieTimeout = 300000000000
GasPrice = 1000000
EnablePreimageRecording = false

[Ptn.TxPool]
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
FeeLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Node]
DataDir = "./palletone"
IPCPath = "gptn.ipc"
HTTPHost = "localhost"
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "ptn"]
WSHost = "localhost"
WSPort = 8546
WSModules = ["net", "web3", "ptn"]

[Dashboard]
Host = "localhost"
Port = 8080
Refresh = 5000000000

[MediatorPlugin]
EnableStaleProduction = false

[[MediatorPlugin.Mediators]]
Address = "P1Kp2hcLhGEP45Xgx7vmSrE37QXunJUd8gJ"
Password = "password"
InitPartSec = "47gsj9pK3pwYUS1ZrWQjTgWMHUXWdNuCr7hXPXHySyBk"
InitPartPub = "XmMwxWh6J71HtzndJy37gNDE9zcZqnHANkbxLHfBWYQwfBJyLeWq17kNRRR4bavoe3Brf5oGpWCYByMpbsWk45ymz4kmjU2AZo8Rm3mJ3MQHpdAgTo2nzWmqU3vCTW6qCfviPD1MKu3FJtmaWiLzdavLx831eCBXA1CdaiXAeU5MPcQ"

[Log]
OutputPaths = ["stdout", "./log/all.log"]
ErrorOutputPaths = ["stderr", "./log/error.log"]
OpenModule = ["all", "build", "cmd", "common", "configure", "core", "internal", "ptnclient", "ptnjson", "statistics", "vendor", "wallet"]
LoggerLvl = "DEBUG"
Encoding = "console"
Development = true

[Dag]
DbCache = 0
DbHandles = 0
CacheSource = ""
RedisAddr = ""
RedisPwd = ""
RedisPrefix = ""
RedisDb = 0
UnitTxSize = 1.048576e+06
UtxoIndex = true
MemoryUnitSize = 1280
IrreversibleHeight = 16
WhetherValidateUnitSignature = false
GenesisHash = "0xeb5f66d0289ea0af68860fd5a4d1a0b38389f598ae01008433a5ca9949fcf55c"
PtnAssetHex = "0x77a93ba2d76811e89d048c85900a9e43"
PtnAssetId = [119, 169, 59, 162, 215, 104, 17, 232, 157, 4, 140, 133, 144, 10, 158, 67]

[P2P]
MaxPeers = 25
NoDiscovery = false
BootstrapNodes = []
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
EnableMsgEvents = false

[Ada.Btc]
NetID = 1
Host = "localhost:18332"
RPCUser = "zxl"
RPCPasswd = "123456"
CertPath = ""
WalletPasswd = "1"

[Ada.Eth]
NetID = 1
Rawurl = "\\\\.\\pipe\\geth.ipc"

[Ada.CCInfoKV.test]
CCName = ""

[Ada.CCInfoKV.test.ChainCodeKV]
testk = [116, 101, 115, 116, 118]

[Contract]
ContractFileSystemPath = "./chaincodes"
Address = "127.0.0.1:12345"
ContractExecutetimeout = 20000000000
ContractDeploytimeout = 40000000000
VmEndpoint = "unix:///var/run/docker.sock"
ContractBuilder = "palletone/palletimg"

[Contract.SysContract]
deposit_syscc = "true"
sample_syscc = "true"
