
[Consensus]
Engine="solo"

[Log]
OutputPaths =["stdout","./log/all.log"]
ErrorOutputPaths= ["stderr","./log/error.log"]
LoggerLvl="debug"   # ("debug", "info", "warn","error", "dpanic", "panic", and "fatal")
Encoding="console" # console,json
Development =true

[Dag]
DbPath="./leveldb"
DbName="palletone.db"

[Genesis]
TotalSupply= 10000000000
HolderAddress="P1B9YK6yYe9YDgiFN89PxkkHE9WCKBbJcNK"   #Private key: bb6ec6e84251e5f7bf35aeb6d0c7e56051d6319d4fd25cd19a9d209f4973765f