[Ptn]
NetworkId = 1
SyncMode = "fast"
NoPruning = false
LightPeers = 100
DatabaseCache = 768
TrieCache = 256
TrieTimeout = 300000000000
GasPrice = 1000000
EnablePreimageRecording = false

[TxPool]
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
FeeLimit = 1
PriceBump = 10
GlobalSlots = 48192
GlobalQueue = 12048
Lifetime = 10800000000000
Removetime = 1800000000000
OrphanTTL = 900000000000
MaxOrphanTxs = 10000
MaxOrphanTxSize = 2000000

[Node]
DataDir = "./palletone"
IPCPath = "gptn.ipc"
HTTPHost = "localhost"
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "wallet", "dag", "personal", "mediator", "ptn"]
WSHost = "localhost"
WSPort = 8546
WSModules = ["net", "web3", "dag", "mediator", "ptn"]

[Dashboard]
Host = "localhost"
Port = 8080
Refresh = 5000000000

[Jury]
ContractSigNum = 1
ElectionNum = 4

[[Jury.Accounts]]
Address = "P1Ca6JxTSPNU4zPb6iTXRMV3UM3HqwHQRcQ"
Password = "1"

[MediatorPlugin]
EnableProducing = true
EnableStaleProduction = true
EnableConsecutiveProduction = false
RequiredParticipation = 0
EnableGroupSigning = true

[[MediatorPlugin.Mediators]]
Address = "P1Ca6JxTSPNU4zPb6iTXRMV3UM3HqwHQRcQ"
Password = "1"
InitPrivKey = "9XSJyLAdivJQPwgSwoPpBPvtHrWAg4YvpwfRHABzdp5J"
InitPubKey = "hHH4uTmHrhDmWWQ4thSSp37vAe7rrDJVdfASNiL6B94h5iffNUg1jGuEcWRDupspM3z7TTS8cZExHYr61icJy4ydS63Agvoh77YpjYMHW1EGKSZM1cGNcQz5JDtM3vXx5Jfw8yCaR5zRhPhnZqa5JM681KqdsAyZGQmknSrRFsxJbfq"

[[MediatorPlugin.Mediators]]
Address = "P15ABuRNZQYu9y5nWgo4nWBBMSZhCsqssrg"
Password = "1"
InitPrivKey = "soQRm1v8CJkBiRU6Vd9YahDjaBEpdj5JfuMnK48sNUE"
InitPubKey = "eT58Ev7mFAMCgpCDi2gfAfFzgypRrnCjMxgmMUqHk8KFT5Y2fWQ6VRKpkXApcX77F5bxFwv5xSirLpbM4m3pTkMfBayzp2JemY1Z3hxP2Qcvcc2pqAYrRjShVWd69mKEss5LREmfVCMKu8L3cEYqXt1gw7VHds46UhZBAEJLK9R7eRR"

[[MediatorPlugin.Mediators]]
Address = "P13ucxmE9iefjaUiht9skbMVvPBzispgphK"
Password = "1"
InitPrivKey = "2a1UgJzeDNKYQJUeLXZCcn7ny1HuLCbxc2fvjLMd49uM"
InitPubKey = "eXbKwA2dXoXJPUXJWP1DrvHdUbzdk2PgVYXx6zFTHfLDNobXRwtfnCAHJPZThbZgtSDjAGXVp8g1Kei7KccUwhisQ7hA72cmFAz84TPkP5aFDLv5n8MmS567TxWG2gAMtknHRsACReLhxryJihCodaES6PJ7pFFe2QqwbzLX4A4LEpc"

[[MediatorPlugin.Mediators]]
Address = "P1PwohNrSR7QcGhwhfNycc8a8nQ6nF1ZvRJ"
Password = "1"
InitPrivKey = "4VkFc9ToJX46PomtGXHJb5hef3q1ChMxVjww1FgSQCN7"
InitPubKey = "gf8vpdVftiZkvSaN62hwsMW2oQNHViyE75zmVxKdmRz4JqJ284wGQepM9aCpCLrzFV9MH5YTLKYEtFMNdx6WetUajS8PnPh4ok97T8cuyE1KP5GzstEaA96GhJakCyniuCYE7dtEFNiSPK8FkzWauV9z29RzZsZgJLEr6mFzdgyqoDa"

[[MediatorPlugin.Mediators]]
Address = "P1dBr3SSpMaRrXixZuE1S4eUbaCDbpadp6"
Password = "1"
InitPrivKey = "7iRwX8ykHubYJS6Xdcg7Y5MjH7YMrAgvSTk2fFA1xqHY"
InitPubKey = "hnxSWKhk7VtEPZTERtxziwpd1jymgjZFvN4BCwPStcHDBMQnD4ZJ23SY3K5XJcu3aQ25yPeJ8DaibTuCgHy3Sa1ZfFa2kfqyTCRp6pKaZVAh4iKgMpKL9PqYjimL1gX7iQymSXT3GGVeRpLuTKWkcGvM8UxjCHTKCEggnRgra3yJLTe"

[Log]
OutputPaths = ["stdout", "./log/all.log"]
ErrorOutputPaths = ["stderr", "./log/error.log"]
OpenModule = ["all"]
LoggerLvl = "DEBUG"
Encoding = "console"
Development = true
RotationMaxSize = 500
RotationMaxAge = 28

[Dag]
DbPath = "./leveldb"
DbCache = 0
DbHandles = 0
CacheSource = ""
RedisAddr = ""
RedisPwd = ""
RedisPrefix = ""
RedisDb = 0
UnitTxSize = 5.12e+06
UtxoIndex = true
MemoryUnitSize = 1280
IrreversibleHeight = 1
WhetherValidateUnitSignature = false
GenesisHash = "0xeb5f66d0289ea0af68860fd5a4d1a0b38389f598ae01008433a5ca9949fcf55c"
PtnAssetHex = "PTN"
PtnAssetId = [64, 0, 130, 187, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
IsRewardCoin = false
AddrTxsIndex = false
Token721TxIndex = true
TextFileHashIndex = false
GasToken = "PTN"
MainToken = "PTN"
SyncPartitionTokens = []

[P2P]
MaxPeers = 25
NoDiscovery = false
BootstrapNodes = []
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
EnableMsgEvents = false

[Ada.Btc]
NetID = 1
BtcHost = "localhost:18332"
RPCUser = "zxl"
RPCPasswd = "123456"
CertPath = ""
WalletPasswd = "1"

[Ada.Eth]
NetID = 1
Rawurl = "\\\\.\\pipe\\geth.ipc"

[Ada.CCInfoKV.test]
CCName = ""

[Ada.CCInfoKV.test.ChainCodeKV]
testk = [116, 101, 115, 116, 118]

[Contract]
ContractFileSystemPath = "./chaincodes"
ContractAddress = "127.0.0.1:12345"
ContractExecutetimeout = 20000000000
ContractDeploytimeout = 40000000000
VmEndpoint = "unix:///var/run/docker.sock"
ContractBuilder = "palletone/goimg"

[Contract.SysContract]
createToken_sycc = "true"
deposit_syscc = "true"
sample_syscc = "true"
