[Ptn]
NetworkId = 1
SyncMode = "fast"
NoPruning = false
LightPeers = 100
DatabaseCache = 768
TrieCache = 256
TrieTimeout = 300000000000
GasPrice = 1000000
EnablePreimageRecording = false

[TxPool]
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
FeeLimit = 1
PriceBump = 10
GlobalSlots = 8192
GlobalQueue = 2048
Lifetime = 10800000000000
Removetime = 1800000000000
OrphanTTL = 900000000000
MaxOrphanTxs = 10000
MaxOrphanTxSize = 2000000

[Node]
DataDir = "./palletone"
IPCPath = "gptn.ipc"
HTTPHost = "localhost"
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "wallet", "dag", "personal", "mediator", "ptn"]
WSHost = "localhost"
WSPort = 8546
WSModules = ["net", "web3", "dag", "mediator", "ptn"]

[Dashboard]
Host = "localhost"
Port = 8080
Refresh = 5000000000

[Jury]
ContractSigNum = 1
ElectionNum = 4

[[Jury.Accounts]]
Address = "P1F5nbVubkAquaBYSoYi7385gn5UYz79x5Y"
Password = "1"

[MediatorPlugin]
EnableProducing = true
EnableStaleProduction = true
EnableConsecutiveProduction = false
RequiredParticipation = 0
EnableGroupSigning = true

[[MediatorPlugin.Mediators]]
Address = "P1F5nbVubkAquaBYSoYi7385gn5UYz79x5Y"
Password = "1"
InitPrivKey = "ABevidChMhn6Uuubm45ALmDSxUE6Yirgb1rweQwfyHa5"
InitPubKey = "TF9RTGE1XRyAdgLBL81NsGFXeHVTGVLk4KiUCqGP9Q565gHczh7ASdptWtzsmkBcicPNfEmEmvgKJR4niMsgAiaJoLo9yWZXHqjfmDAj9byn6xYV6p2gxaHMSpPyXeJYyt4raSF6vGNymoXiG7LkQWdNW4tkJTBkW6MQSLFnXr9a3tf"

[[MediatorPlugin.Mediators]]
Address = "P16LPc7ZgZr5WWALVQSSg8toPvoVjYXQkxr"
Password = "1"
InitPrivKey = "2ZGWofDXdKz9oD7WsSdZC15n1nP16S6gKuuENmSStGhw"
InitPubKey = "dJ1NziFRo75srfqs9SXxVqmqv5nof9GvW8aCpTBbqPz8PD9kZoApDWktBYK7dq61JSPHXUeUATfcACRSp8XtZ1de6s6Asr2FoqW5HN5E9WJzHNBGR7VS1Amqwv4i36fpy2VVRyFhkk4knCNcafVbKxeHXRqqdZVeaWKYYvUAzxZFocA"

[[MediatorPlugin.Mediators]]
Address = "P12myeS8B3QFSBz5WH4ySimomnChAVyD3DE"
Password = "1"
InitPrivKey = "769kV2ikF7Ym35LRRessBBHRR7ZZNT1VwATnuqinpwcb"
InitPubKey = "WMMKaRrkYLVEbAGRbNXn43sD5fT65vhHcJhMk2xyDZGfaCi5VoCwiVeJL5yqbh56zjPgotM3qddVQNTU3hzwPuXiX4WJeQkMVVXzQSXr9zSKcovvxhRbHF9PeTL4Q8Yhkc5SVV8zCbPG2xY6pZyUk7DmufcEaYb9fBPe9JckxGhKJme"

[[MediatorPlugin.Mediators]]
Address = "P1FxaU7Qom6qkCmPBYgsAHDbQfPEbwTjQip"
Password = "1"
InitPrivKey = "2zv94mSGpKgugUnBUNKStwJqcxRs5wP8zuJ6DoJaE4Y8"
InitPubKey = "aQfN2we9rtZLBwQmMiVx2V6vWyecxGGMSnG3HhmTazS55SQ2TBDvtoez81bzkGsXfA8pzJoBZGtg4PSVtgpxKEUBd2xpUZesF75x99CExQeeqdLL9tKetdbMC6Pn3uSiJgErvvMv3pnz8whtCnWc9QX1VF6CvZKewD2UgNMtgSA3kX5"

[[MediatorPlugin.Mediators]]
Address = "P1EZvT7bT5DFs8QAXAhuYLKUjFaejWcCG68"
Password = "1"
InitPrivKey = "9f42Xh5TZaG4sym6hHuA5JTQ6x8VGgtqCJ9YXNuEnq9K"
InitPubKey = "Wc4cRFtuSKj2x7nYdQbgYJC8PVivddt9QFJNxh6fAAsbUSPFhH46EQgyEqRpQR4Ci66myytGMM9ET1EoABMEBCk1bd2vmU7GHe3NgKaGqikmuLDXcyimPNsbhivd8Q1vRpziEtKZETQSrsoJbMtH8zGkoGfcdGY3YgZbJgCS12HMjmj"

[Log]
OutputPaths = ["stdout", "./log/all.log"]
ErrorOutputPaths = ["stderr", "./log/error.log"]
OpenModule = ["all"]
LoggerLvl = "DEBUG"
Encoding = "console"
Development = true
RotationMaxSize = 500
RotationMaxAge = 28

[Dag]
DbPath = "./leveldb"
DbCache = 0
DbHandles = 0
CacheSource = ""
RedisAddr = ""
RedisPwd = ""
RedisPrefix = ""
RedisDb = 0
UnitTxSize = 1.048576e+06
UtxoIndex = true
MemoryUnitSize = 1280
IrreversibleHeight = 1
WhetherValidateUnitSignature = false
GenesisHash = "0xeb5f66d0289ea0af68860fd5a4d1a0b38389f598ae01008433a5ca9949fcf55c"
PtnAssetHex = "400082bb080000000000000000000000"
PtnAssetId = [64, 0, 130, 187, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
IsRewardCoin = false
AddrTxsIndex = false
TextFileHashIndex = false
GasToken = "PTN"
MainToken = "PTN"
SyncPartitionTokens = []

[P2P]
MaxPeers = 25
NoDiscovery = false
BootstrapNodes = []
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
EnableMsgEvents = false

[Ada.Btc]
NetID = 1
BtcHost = "localhost:18332"
RPCUser = "zxl"
RPCPasswd = "123456"
CertPath = ""
WalletPasswd = "1"

[Ada.Eth]
NetID = 1
Rawurl = "\\\\.\\pipe\\geth.ipc"

[Ada.CCInfoKV.test]
CCName = ""

[Ada.CCInfoKV.test.ChainCodeKV]
testk = [116, 101, 115, 116, 118]

[Contract]
ContractFileSystemPath = "./chaincodes"
ContractAddress = "127.0.0.1:12345"
ContractExecutetimeout = 20000000000
ContractDeploytimeout = 40000000000
VmEndpoint = "unix:///var/run/docker.sock"
ContractBuilder = "palletone/goimg"

[Contract.SysContract]
createToken_sycc = "true"
deposit_syscc = "true"
sample_syscc = "true"
