
[Consensus]
Engine="solo"

[Log]
OutputPaths =["stdout","./log/all.log"]
ErrorOutputPaths= ["stderr","./log/error.log"]
LoggerLvl="debug"   # ("debug", "info", "warn","error", "dpanic", "panic", and "fatal")
Encoding="console" # console,json
Development =true

[Dag]
DbPath="./leveldb"
DbName="palletone.db"

[Node]
DataDir = "./data1"
KeyStoreDir="./data1/keystore"
IPCPath = "gpan.ipc"