[Ada.Btc]
NetID = 1
Host = "localhost:18332"
RPCUser = "zxl"
RPCPasswd = "123456"
CertPath = ""
WalletPasswd = "1"

[Ada.Btc.ChaincodeKeys]
sample_syscc = "cQex5TCk5xgSkdjHALNSFP9JJNtwo87yzYLfiAC954nxKi2BxUS7"

[Ada.Btc.AddressKeys]
mqdyHp3U1UBk8suERTqHFbedKx2vi36XCd = "cQex5TCk5xgSkdjHALNSFP9JJNtwo87yzYLfiAC954nxKi2BxUS7"

[Ada.Eth]
NetID = 1
Rawurl = "\\\\.\\pipe\\geth.ipc"

[Ada.CCInfoKV.test]
CCName = ""

[Ada.CCInfoKV.test.ChainCodeKV]
testk = [116, 101, 115, 116, 118]
